#!/bin/bash

# 
# pybind11
# 

export PYTHON37=/Library/Frameworks/Python.framework/Versions/3.7/bin
export PYTHON_EXECUTABLE=${PYTHON37}/python3

cmake -S . -B build \
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=OFF \
-DTRAPPER_BUILD_ADVANCED_EXAMPLES=OFF \
\
-DTRAPPER_BUILD_MMG_EXAMPLE=OFF \
-DTRAPPER_BUILD_EMBREE_EXAMPLE=OFF \
-DTRAPPER_BUILD_DLIB_EXAMPLE=OFF \
-DTRAPPER_BUILD_POLYSCOPE_EXAMPLE=OFF \
-DTRAPPER_BUILD_IMGUI_EXAMPLE=OFF \
-DTRAPPER_BUILD_PYBIND11_EXAMPLE=OFF \
\
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=ON \
-DTRAPPER_BUILD_PYBIND11_EXAMPLE=ON \
\
-DPYBIND11_INSTALL=ON \
-DPYBIND11_TEST=OFF \
-DDOWNLOAD_EIGEN=OFF \
-DEigen3_DIR=/usr/local/share/eigen3/cmake \
-DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}

cmake --build build

${PYTHON_EXECUTABLE} $(pwd)/examples/default/pybind11/run.py
${PYTHON_EXECUTABLE} $(pwd)/examples/default/pybind11/main.py

# TODO: download eigen
# TODO: download python37

