#!/bin/bash

# 
# Dlib
# 

cmake -S . -B build \
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=OFF \
-DTRAPPER_BUILD_ADVANCED_EXAMPLES=OFF \
-DTRAPPER_BUILD_MMG_EXAMPLE=OFF \
-DTRAPPER_BUILD_EMBREE_EXAMPLE=OFF \
-DTRAPPER_BUILD_DLIB_EXAMPLE=OFF \
-DTRAPPER_BUILD_POLYSCOPE_EXAMPLE=OFF \
-DTRAPPER_BUILD_IMGUI_EXAMPLE=OFF \
 \
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=ON \
-DTRAPPER_BUILD_DLIB_EXAMPLE=ON \
\
-DDLIB_GIF_SUPPORT=ON \
-DDLIB_JPEG_SUPPORT=ON \
-DDLIB_PNG_SUPPORT=ON \
-DDLIB_USE_BLAS=ON \
-DDLIB_USE_CUDA=OFF \
-DDLIB_USE_LAPACK=ON \
-DDLIB_USE_MKL_FFT=OFF \
-DDLIB_LINK_WITH_SQLITE3=OFF \
-DDLIB_NO_GUI_SUPPORT=OFF \
-DDLIB_ENABLE_ASSERTS=OFF \
-DDLIB_ENABLE_STACK_TRACE=OFF

cmake --build build

