
del /S /Q .\build\CMakeCache.txt

cmake -S . -B build -G Ninja ^
-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE ^
-DCMAKE_BUILD_TYPE=RELEASE ^
 ^
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=OFF ^
-DTRAPPER_BUILD_ADVANCED_EXAMPLES=OFF ^
-DTRAPPER_BUILD_EMBREE_EXAMPLE=OFF ^
-DTRAPPER_BUILD_DLIB_EXAMPLE=OFF ^
-DTRAPPER_BUILD_POLYSCOPE_EXAMPLE=OFF ^
-DTRAPPER_BUILD_IMGUI_EXAMPLE=OFF ^
-DTRAPPER_BUILD_NANOFLANN_EXAMPLE=OFF ^
-DTRAPPER_BUILD_LIBZIPPP_EXAMPLE=OFF ^
 ^
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=ON ^
-DTRAPPER_BUILD_MMG_EXAMPLE=ON ^
 ^
-DBUILD=MMG2D ^
-DBUILD_SHARED_LIBS=ON ^
-DLIBMMG2D_SHARED=ON ^
-DLIBMMG2D_STATIC=OFF ^
-DBUILD_TESTING=OFF ^
-DTEST_LIBMMG2D=OFF ^
-DUSE_SCOTCH=OFF ^
-DUSE_ELAS=OFF ^
-DUSE_VTK=OFF

cmake --build build
