#!/bin/bash

# 
# MMG
# 

cmake -S . -B build \
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=OFF \
-DTRAPPER_BUILD_ADVANCED_EXAMPLES=OFF \
-DTRAPPER_BUILD_MMG_EXAMPLE=OFF \
-DTRAPPER_BUILD_EMBREE_EXAMPLE=OFF \
-DTRAPPER_BUILD_DLIB_EXAMPLE=OFF \
-DTRAPPER_BUILD_POLYSCOPE_EXAMPLE=OFF \
-DTRAPPER_BUILD_IMGUI_EXAMPLE=OFF \
 \
-DTRAPPER_BUILD_DEFAULT_EXAMPLES=ON \
-DTRAPPER_BUILD_MMG_EXAMPLE=ON \
\
-DBUILD=MMG2D \
-DLIBMMG2D_STATIC=OFF \
-DLIBMMG2D_SHARED=ON \
-DUSE_SCOTCH=OFF \
-DUSE_ELAS=OFF \
-DUSE_VTK=OFF

cmake --build build



